szim_admin:
    resource: "@SZIMAdminBundle/Resources/config/routing.yml"
    prefix:   /

szim_program:
    resource: "@SZIMProgramBundle/Resources/config/routing.yml"
    prefix:   /program

szim_main:
    resource: "@SZIMMainBundle/Resources/config/routing.yml"
    prefix:   /

