parameters:
#    szim_program.example.class: SZIM\ProgramBundle\Example

services:
#    szim_program.example:
#        class: %szim_program.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
