szim_create_test_data:
    pattern:  /testdata
    defaults: { _controller: SZIMMainBundle:Default:testdata }

szim_main_homepage:
    pattern:  /{page}
    defaults: { _controller: SZIMMainBundle:Default:index }


